### PR TITLE
Update information

### PR DESCRIPTION
**Pull request by Puneetsingh25**

### CODE REVIEW

**Comment by svenska-primekey** [comment]
@Puneetsingh25 why do you keep creating a new pull request instead of updating a currently open pull request? Who should be listed as representative? The PR removes the representative and would not list anyone.

**Comment by Puneetsingh25** [comment]
@***@***.***> : Can you please look into it?

Thank you,

Puneet Singh
Principal
Encryption Consulting LLC
email: ***@***.******@***.***>
Tel: +1 469 815 4136
Cell: +1 469 400 7592
130 N Preston Rd, Prosper TX 75078

**Comment by Puneetsingh25** [comment]
Hello Team,

Sorry for creating a new pull request. The pull request I made isn't updating with the new information, it shows 'Merging is blocked. The base branch restricts merging to authorized users.' How can I overcome this issue? How do I update the information in https://github.com/pkic/pkic.org/blob/main/data/members/encryptionconsulting.yaml? Could you please provide a solution? I have also attached a screenshot for reference.

***@***.***



Thank you,

Nischinth
Consultant
Encryption Consulting LLC
email: ***@***.******@***.***>
Tel: +1 469 815 4136
130 N Preston Rd, Prosper TX 75078
www.encryptionconsulting.com<http://www.encryptionconsulting.com/>

From: Puneet ***@***.***>
Sent: Tuesday, July 23, 2024 9:33 PM
To: pkic/pkic.org ***@***.***>; pkic/pkic.org ***@***.***>; Nischinth ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [pkic/pkic.org] Update information (PR #166)

@***@***.***> : Can you please look into it?

Thank you,

Puneet Singh
Principal
Encryption Consulting LLC
email: ***@***.******@***.***>
Tel: +1 469 815 4136
Cell: +1 469 400 7592
130 N Preston Rd, Prosper TX 75078

**Comment by Puneetsingh25** [comment]
Hello All-

Any update on the below request? How can we update our information?

Thank you,

Puneet Singh
Principal
Encryption Consulting LLC
email: ***@***.******@***.***>
Tel: +1 469 815 4136
Cell: +1 469 400 7592
130 N Preston Rd, Prosper TX 75078

From: Nischinth ***@***.***>
Sent: Tuesday, July 23, 2024 11:14 AM
To: pkic/pkic.org ***@***.***>; pkic/pkic.org ***@***.***>
Cc: Mention ***@***.***>; Puneet ***@***.***>
Subject: RE: [pkic/pkic.org] Update information (PR #166)

Hello Team,

Sorry for creating a new pull request. The pull request I made isn't updating with the new information, it shows 'Merging is blocked. The base branch restricts merging to authorized users.' How can I overcome this issue? How do I update the information in https://github.com/pkic/pkic.org/blob/main/data/members/encryptionconsulting.yaml? Could you please provide a solution? I have also attached a screenshot for reference.

***@***.***



Thank you,

Nischinth
Consultant
Encryption Consulting LLC
email: ***@***.******@***.***>
Tel: +1 469 815 4136
130 N Preston Rd, Prosper TX 75078
www.encryptionconsulting.com<http://www.encryptionconsulting.com/>

From: Puneet ***@***.******@***.***>>
Sent: Tuesday, July 23, 2024 9:33 PM
To: pkic/pkic.org ***@***.******@***.***>>; pkic/pkic.org ***@***.******@***.***>>; Nischinth ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [pkic/pkic.org] Update information (PR #166)

@***@***.***> : Can you please look into it?

Thank you,

Puneet Singh
Principal
Encryption Consulting LLC
email: ***@***.******@***.***>
Tel: +1 469 815 4136
Cell: +1 469 400 7592
130 N Preston Rd, Prosper TX 75078

**Comment by svenska-primekey** [comment]
The changes are reviewed and then approved by Paul or I. Who should be listed as representative since the PR removes you? Do you want no one listed as a representative for Encryption Consulting?

**Comment by Puneetsingh25** [comment]
Right now you can remove me from there and we are right making decision on rebuilding leadership team. When we have a decision we will update again.

Thank you,

Puneet Singh
Principal
Encryption Consulting LLC
email: ***@***.******@***.***>
Tel: +1 469 815 4136
Cell: +1 469 400 7592
130 N Preston Rd, Prosper TX 75078

**Comment by svenska-primekey** [comment]
Fixing in #192

**Pull request closed without merging**
